/** @type {import('tailwindcss').Config} */
module.exports = {
content: [
    "./index.html",
    "./scripts/**/*.js", // أي ملفات JS اللي فيها dynamic content
  ],
  safelist: [
    "bg-white",
    "dark:bg-gray-800",
    "group",
    "p-2",
    "cursor-pointer",
    "transition-all",
    "duration-300",
    "hover:-translate-y-1",
    "border",
    "border-gray-300",
    "dark:border-gray-500",
    "rounded-xl",
    "bg-rose-400",
    "rounded-t-xl",
    "overflow-hidden",
    "w-full",
    "group-hover:scale-105",
    "sm:h-52",
    "object-cover",
    "px-3",
    "space-y-3",
    "rounded-b-xl",
    "pb-3",
    "mt-3",
    "flex",
    "items-center",
    "justify-between",
    "text-gray-800",
    "dark:text-gray-200",
    "text-lg",
    "text-xs",
    "px-3",
    "py-1",
    "bg-blue-100",
    "text-blue-700",
    "rounded-full",
    "text-sm",
    "text-gray-600",
    "dark:text-gray-400",
    "h-20",
    "flex",
    "gap-3",
    "text-white",
    "bg-gradient-to-t",
    "from-blue-500",
    "to-blue-400",
    "dark:bg-gradient-to-t",
    "dark:from-rose-700",
    "dark:to-rose-600",
    "rounded-xl",
    "w-full",
    "bg-gray-800",
    "hover:bg-black",
    "dark:hover:bg-white",
    "dark:hover:text-black",
    "cursor-pointer",
    "flex",
    "items-center",
    "justify-center",
    "w-12",
    "rounded-full",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
